version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    hostname: 127.0.0.1
    ports:
      - "8761:8761"
    networks:
      - cursoms-network

  cursoms-avaliadorcredito:
    build:
      context: ./msavaliadorcredito
      dockerfile: Dockerfile
    container_name: cursoms-avaliadorcredito
    environment:
      RABBITMQ_SERVER: cursoms-rabbitmq
      EUREKA_SERVER: eureka-server
    hostname: 127.0.0.1
    networks:
      - cursoms-network

  cursoms-cartoes:
    build:
      context: ./mscartoes
      dockerfile: Dockerfile
    container_name: cursoms-cartoes
    environment:
      EUREKA_SERVER: eureka-server
      RABBITMQ_SERVER: cursoms-rabbitmq
    hostname: 127.0.0.1
    networks:
      - cursoms-network

  cursoms-clientes:
    build:
      context: ./msclientes
      dockerfile: Dockerfile
    container_name: cursoms-clientes
    environment:
      EUREKA_SERVER: eureka-server
    hostname: 127.0.0.1
    networks:
      - cursoms-network

  cursoms-gateway:
    build:
      context: ./mscloudgateway
      dockerfile: Dockerfile
    container_name: cursoms-gateway
    environment:
      EUREKA_SERVER: eureka-server
      KEYCLOAK_SERVER: 127.0.0.1
      KEYCLOAK_PORT: 8081
    hostname: 127.0.0.1
    ports:
      - "8080:8080"
    networks:
      - cursoms-network

  cursoms-keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: cursoms-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    hostname: 127.0.0.1
    ports:
      - "8081:8080"
    networks:
      - cursoms-network

  cursoms-rabbitmq:
    image: rabbitmq:3.9-management
    container_name: cursoms-rabbitmq
    hostname: 127.0.0.1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cursoms-network

networks:
  cursoms-network:
    driver: bridge