spring:
  application:
    name: eurikaserver
  security:
    basic:
        enabled: true
    user:
      name: admin
      password: admin

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false